error:
  whitelabel:
    enabled: true

amazon:
  associate_id: habuma-20

logging:
  level:
    root: DEBUG

#spring:
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true


